### ISSUE TITLE
Viewstate delete fails

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/seadbrowserclient#124]
Server error:

handleViewstateDelete
Warning: no saslprep library specified. Passwords will not be sanitized
Connected to db server
/sqs_viewstate_server/node_modules/mongodb/lib/utils.js:133
      throw err;
      ^

TypeError: Cannot read property 'user' of undefined
    at /sqs_viewstate_server/src/router.js:78:43
    at /sqs_viewstate_server/node_modules/mongodb/lib/operations/execute_operation.js:86:17
    at executeCallback (/sqs_viewstate_server/node_modules/mongodb/lib/operations/execute_operation.js:79:9)
    at handleCallback (/sqs_viewstate_server/node_modules/mongodb/lib/utils.js:129:55)
    at /sqs_viewstate_server/node_modules/mongodb/lib/operations/to_array.js:36:13
    at handleCallback (/sqs_viewstate_server/node_modules/mongodb/lib/utils.js:129:55)
    at completeClose (/sqs_viewstate_server/node_modules/mongodb/lib/cursor.js:859:16)
    at Cursor.close (/sqs_viewstate_server/node_modules/mongodb/lib/cursor.js:878:12)
    at /sqs_viewstate_server/node_modules/mongodb/lib/operations/to_array.js:35:25
    at /sqs_viewstate_server/node_modules/mongodb/lib/core/cursor.js:750:9

**Comment by johanvonboer** [comment]
Can't reproduce - it now works again. It could have been that I just messed it up temporarily on my local machine when re-ordering the vs table columns, perhaps resulting in the wrong ID being sent to the server.
